application: textbookcomments
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /
  script: home.py

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /css/images
  static_dir: static/css/images

- url: /.*
  script: home.py